mappings:
  TableFilterSortServerSaverController: Sunnysideup\TableFilterSort\Control\TableFilterSortServerSaverController
  TableFilterSortModelAdmin: Sunnysideup\TableFilterSort\Cms\TableFilterSortModelAdmin
  TableFilterSortAPI: Sunnysideup\TableFilterSort\Api\TableFilterSortAPI
  TableFilterSortServerSaver: Sunnysideup\TableFilterSort\Model\TableFilterSortServerSaver
  TableFilterSortTag: Sunnysideup\TableFilterSort\Model\TableFilterSortTag
