---
Name: 'TableFilterSortRoutes'
After: framework
---
SilverStripe\Control\Director:
  rules:
    'tfs//$Action/$ID/$OtherID/$Version': Sunnysideup\TableFilterSort\Control\TableFilterSortServerSaverController
